networks:
  counter-net:

volumes:
  counter-vol:
  
services:
  web-fe:
    image: nigelpoulton/gsd:swarm2023
    command: python app.py
    deploy:
      replicas 10
    ports:
      - target: 8080
        published: 5001
    networks:
      - counter-net
    volumes:
      - type: volume
        source: counter-vol
        target: /app
  redis:
    image: "redis:alpine"
    networks:
      counter-net:

